audio_stop_all();
global.birdName = "";
global.bird1_text = "Capuchinbird";
global.bird2_text = "Green jay";
global.bird3_text = "Toco Toucan";
global.bird4_text = "Waved Albatross";
global.bird5_text = "Hyacinth Macaw";
global.bird1_sound = snd_Capuchinbird;
global.bird2_sound = snd_Greenjay;
global.bird3_sound = snd_Toucan;
global.bird4_sound = snd_Albatross;
global.bird5_sound = snd_Macaw;
bird1.sprite_index = capuchinbird;
bird2.sprite_index = greenjay;
bird3.sprite_index = toucan;
bird4.sprite_index = albatross;
bird5.sprite_index = macaw;